### ISSUE TITLE
[Feat]: 对于gpt-4-mobile的画图功能，返回的是prompt 英文文字+图案地址，如何只发送图片（不是下载链接）

### ISSUE THREAD

**Issue by spacex-3** [iuiaoin/wechat-gptbot#106]
### Search for answers in existing issues

- [X] I have searched issues, there is no similar issue related

### Feature description

我是用的https://github.com/Ink-Osier/PandoraToV1Api，把pandora的proxy api转为可以画图的api

我发送消息：画一个可爱的小恐龙

机器人回复：
```
{"prompt":"A cute cartoon dinosaur, with bright green scales and big, expressive eyes. It has a friendly smile, small arms, and a long tail. The dinosaur stands in a playful pose in a lush, colorful prehistoric landscape with ferns and prehistoric plants. The sky is clear and blue. The scene exudes a cheerful and child-friendly atmosphere.","size":"1024x1024"}
```

![image](https://image.****/images/image_20231216153418.png)
[下载链接](https://image.****/images/image_20231216153418.png)
Here's the illustration of a cute cartoon dinosaur that I created for you!

### Motivation

希望可以去掉prompt，只下载图片并发送图片

**Comment by spacex-3** [comment]
这个问题已经通过转换解决。不过还是对于自定义模型名字有疑问。

比如gpt-4-mobile，这个就无法使用了

**Comment by QAbot-zh** [comment]
逆向模型就自己改改吧，不是官方模型返回响应不稳定

**Comment by spacex-3** [comment]
> 逆向模型就自己改改吧，不是官方模型返回响应不稳定

是的，改了映射了。
