### ISSUE TITLE
[Bug]: wechat.py中的问题

### ISSUE THREAD

**Issue by moumouy** [iuiaoin/wechat-gptbot#14]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.10

### Issue description

启动app.py后，使用两个不同的个人微信号与登录的这个微信号对话。其中一个可以正常获取gpt的回答，另一个会被识别为公众号消息被忽略“message sent by public/subscription account, ignore”，请问如何修复这个问题？
另外，是否可以设定开启文字回复的唤醒词？谢谢

**Comment by beanbear** [comment]
正想开一个issue，询问大佬是否可以设定唤醒词，避免私聊会直接触发gpt，谢谢大佬！

**Comment by iuiaoin** [comment]
被识别公众号只有两种情况
1. id不是以"wxid"开头
2. id不存在
有问题的那个微信号是新号吗？如果没有设置过微信号需要设置一下, 参考[#3](https://github.com/iuiaoin/wechat-gptbot/issues/3#issuecomment-1580984247)

**Comment by iuiaoin** [comment]
@beanbear ok的, 唤醒词可以加

**Comment by iuiaoin** [comment]
@beanbear Done with the pull request [#15](https://github.com/iuiaoin/wechat-gptbot/pull/15)

**Comment by moumouy** [comment]
> 被识别公众号只有两种情况
> 
> 1. id不是以"wxid"开头
> 2. id不存在
> 
> 有问题的那个微信号是新号吗？如果没有设置过微信号需要设置一下, 参考[#3](https://github.com/iuiaoin/wechat-gptbot/issues/3#issuecomment-1580984247)

这就奇怪了，有问题的反而是天天使用的主号，早就换过id了，没问题的是那些小号，当然也都自定义过id

**Comment by iuiaoin** [comment]
@moumouy 可以在[这一行](https://github.com/iuiaoin/wechat-gptbot/blob/59a844c01f40022e8dd26b21e15ab37e5685f599/channel/wechat.py#LL107C9-L107C32)下面加条log看一下sender_id是否正常

**Comment by goxofy** [comment]
我也有同样问题，日常使用的微信号

**Comment by iuiaoin** [comment]
> @moumouy 可以在[这一行](https://github.com/iuiaoin/wechat-gptbot/blob/59a844c01f40022e8dd26b21e15ab37e5685f599/channel/wechat.py#LL107C9-L107C32)下面加条log看一下sender_id是否正常

@goxofy 在上面的位置加一行`logger.info(f"sender_id: {sender_id}")`, 重启程序后用有问题的微信号发消息给bot试下看看打出的sender_id是否是以"wxid"开头的字符串?

**Comment by moumouy** [comment]
> @moumouy 可以在[这一行](https://github.com/iuiaoin/wechat-gptbot/blob/59a844c01f40022e8dd26b21e15ab37e5685f599/channel/wechat.py#LL107C9-L107C32)下面加条log看一下sender_id是否正常

不正常，已自定义微信号
{'content': '你是谁', 'id': '20230612194942', 'id1': '', 'id2': 'mou*****', 'id3': '<msgsource>\n\t<signature>v1_1548OHdB</signature>\n\t<tmp_node>\n\t\t<publisher-id>&lt;![CDATA[]]&gt;</publisher-id>\n\t</tmp_node>\n</msgsource>\n', 'srvid': 1, 'time': '2023-06-12 19:49:42', 'type': 1, 'wxid': 'mou*****'}

正常回复，sender_id以wxid开头
{'content': '你是谁', 'id': '20230612195050', 'id1': '', 'id2': 'wxid_pt7rvwydq****', 'id3': '<msgsource>\n\t<signature>v1_XvaW5w+k</signature>\n\t<tmp_node>\n\t\t<publisher-id>&lt;![CDATA[]]&gt;</publisher-id>\n\t</tmp_node>\n</msgsource>\n', 'srvid': 1, 'time': '2023-06-12 19:50:50', 'type': 1, 'wxid': 'wxid_pt7rvwydq****'}

**Comment by moumouy** [comment]
> > @moumouy 可以在[这一行](https://github.com/iuiaoin/wechat-gptbot/blob/59a844c01f40022e8dd26b21e15ab37e5685f599/channel/wechat.py#LL107C9-L107C32)下面加条log看一下sender_id是否正常
> 
> @goxofy 在上面的位置加一行`logger.info(f"sender_id: {sender_id}")`, 重启程序后用有问题的微信号发消息给bot试下看看打出的sender_id是否是以"wxid"开头的字符串?

如果是过滤公众号的消息，是不是判定id为“gh_*******”才过滤更为正确？gh才是公众号的开头

**Comment by moumouy** [comment]
> @moumouy @goxofy 已修复, 拉取最新的代码试一下?

可以了，感谢
