### ISSUE TITLE
[Bug]: 微信被限制扫码登陆

### ISSUE THREAD

**Issue by Cue-0x00** [iuiaoin/wechat-gptbot#17]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.9

### Issue description

微信被限制扫码登陆

### Repro steps

![Uploading B8BA4C83196BDFEA8BC068C143547223.png…]()

**Comment by Cue-0x00** [comment]
就开启以后加了三个好友就这样了，申请解封又秒封

**Comment by Cue-0x00** [comment]
微信安全提醒
该微信号因当前登录环境存在异常，当前无法使用扫码登录其他设备。该限制为临时限制。

**Comment by iuiaoin** [comment]
@Cue-0x00 windows hook使用的是微信原生的登录方式, 不会改变登录环境，因此通常是以下原因: 

1. 手机号异常: 例如使用的手机是虚拟的号码，或绑定过不活跃的号，或绑过违规号，或存在频繁创建以及换绑行为
2. 登录设备频繁变更：微信在保护用户账户安全方面会对频繁变更设备的行为进行限制，因为这可能是被盗号或恶意操作的标志。
3. 网络环境异常：同个网络地址下存在多号，而且号的资料雷同，被系统判定微信营销网络环境
4. 设备信息异常：如果你的设备被检测为已被root或jailbreak, 以及同个设备存在多个账号，或被封过多次号, 微信可能会限制登录
5. 账户异常行为：如果你的微信账户在**短时间内有大量的添加好友、发广告**等异常行为，微信可能会对你的账户进行限制

**Comment by Cue-0x00** [comment]
应该是加好友的问题
