### ISSUE TITLE
能否支持第三方OpenAI接口代理URL，就是类似下面网址这样的

### ISSUE THREAD

**Issue by himonster1** [iuiaoin/wechat-gptbot#2]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#base_url-%E5%8F%AF%E9%80%89

因为我用的不是官方的api，用的是二道贩子的

**Comment by iuiaoin** [comment]
Replacing url is now supported, try using your third-party api to have a try~

**Comment by himonster1** [comment]
泰库辣
