### ISSUE TITLE
[Bug]: How to send message directly in group? Don't use At msg?

### ISSUE THREAD

**Issue by h3clikejava** [iuiaoin/wechat-gptbot#34]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.8

### Issue description

我的问题有两个：
1. 如何向群里发送普通消息，目前我看代码里需要传入 wxid 和 nickname 构建成一个 const.AT_MSG 。可是我的需求就是发普通的消息而不是At。如果我不传入 wxid 和 nickname 就会出现 @null 的情况。如果我强行写死 const.TXT_MSG ，消息就无法发送到群里。所以如何构建一个往群里发的普通消息？

2. 上哪里查看websocket支持的API和参数？没找到文档。例如 ‘/api/get_personal_info’ 这个请求是在哪里知道的呢？哪里有文档可以查到所有接口和参数呢？

谢谢

**Comment by JimmyGao** [comment]
@h3clikejava 请问您是如何解决的？我也有同样的困惑
