### ISSUE TITLE
[Feat]:可以新增一个对指定用户发送消息的功能吗? 

### ISSUE THREAD

**Issue by q735409242** [iuiaoin/wechat-gptbot#35]
### Search for answers in existing issues

- [X] I have searched issues, there is no similar issue related

### Feature description

如果能有一个接口向指定的wxid发送消息,那就可以不仅仅被动触发啦,可以主动调用做一个小助理了!!如果这个功能可以实现那就泰裤辣~

**Comment by q735409242** [comment]
找到解决方法啦~ 感谢大佬!

**Comment by JERRY871207** [comment]
想问一下是如何解决的
