### ISSUE TITLE
[Feat]: 私聊中，Ai回复可选加前缀

### ISSUE THREAD

**Issue by Ethan-Ming** [iuiaoin/wechat-gptbot#37]
### Search for answers in existing issues

- [X] I have searched issues, there is no similar issue related

### Feature description

有些时候希望能让对方区分出是我还是Ai在回复他

**Comment by q735409242** [comment]
wechat.py里build_msg函数的content加上你要的前缀就可以了

**Comment by undefinedcodezhong** [comment]
https://github.com/iuiaoin/wechat-gptbot/pull/71#issue-1828482249
简单实现了一下

**Comment by iuiaoin** [comment]
Done with #74
