### ISSUE TITLE
希望将收发消息封装成插件形式，方便大家维护[Feat]: 

### ISSUE THREAD

**Issue by zwluoqi** [iuiaoin/wechat-gptbot#38]
### Search for answers in existing issues

- [X] I have searched issues, there is no similar issue related

### Feature description

做了一些功能，但是对代码有些破坏，所以没有PR，希望大佬做成插件形式。方便第三方扩展。

**Comment by iuiaoin** [comment]
这个task其实我早就开了，但一直没时间做🤣，我过两天抽时间做一下

**Comment by iuiaoin** [comment]
Done with [#46](https://github.com/iuiaoin/wechat-gptbot/commit/8b37e4131f0601df5f1935d097c567ec35c7246e)
