### ISSUE TITLE
微信公众号消息触发死循环

### ISSUE THREAD

**Issue by yuefengkai** [iuiaoin/wechat-gptbot#4]
![QQ截图20230607224753](https://github.com/iuiaoin/wechat-gptbot/assets/2100585/d65e3255-1e52-4280-a7cd-81620b32446b)
![QQ截图20230607224800](https://github.com/iuiaoin/wechat-gptbot/assets/2100585/e82cfd6f-5bcb-403d-8f7f-dadb9f1ca7de)

**Comment by q735409242** [comment]
我也发现了 过滤一下wxid就好了  公众要的wxid都带'gh_'

**Comment by q735409242** [comment]
有的也带"wxid_"一并过滤吧 哈哈哈

**Comment by iuiaoin** [comment]
Thanks for the feedback, this issue has been fixed, please update to the latest version.
