### ISSUE TITLE
[Bug]: get_personal_info() failed

### ISSUE THREAD

**Issue by SeaOfSky** [iuiaoin/wechat-gptbot#43]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.10

### Issue description

其他均正常，注册也成功了，也能正常监听消息，但是启动时候不能正常载入 personal info.
[ERROR][2023-07-08 11:39:43][wechat.py:212] - Get personal info failed!
[ERROR][2023-07-08 11:39:43][wechat.py:213] - 'wx_name'
Traceback (most recent call last):
  File "C:\d\llm\wechat-gptbot\channel\wechat.py", line 204, in get_personal_info
    nickName: {content['wx_name']}
KeyError: 'wx_name'

打印response为：
{'content': '[json.exception.type_error.316] invalid UTF-8 byte at index 0: 0xF8', 'id': '20230708113048', 'receiver': 'CLIENT', 'sender': 'SERVER', 'srvid': 1, 'status': 'FAILED', 'time': '2023-07-08 11:30:48', 'type': 6500}

**Comment by iuiaoin** [comment]
Please refer to this [issue](https://github.com/iuiaoin/wechat-gptbot/issues/3#issuecomment-1580984247)
