### ISSUE TITLE
[Bug]: 微信一样会被封禁言

### ISSUE THREAD

**Issue by 1014156094** [iuiaoin/wechat-gptbot#45]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.9

### Issue description

![83930b2b4fa94a959b85a3640467aaaf](https://github.com/iuiaoin/wechat-gptbot/assets/16074662/21ba693b-a2e7-4026-8355-537ab1647a51)
一下突然收到3条，之前一条都没收到过

**Comment by iuiaoin** [comment]
@1014156094  windows hook使用的是微信原生的登录方式, 不会改变登录环境, 如遇微信警告或封禁, 通常是以下原因:

手机号异常: 例如使用的手机是虚拟的号码, 或绑定过不活跃的号, 或绑过违规号, 或存在频繁创建以及换绑行为
登录设备频繁变更: 微信在保护用户账户安全方面会对频繁变更设备的行为进行限制, 因为这可能是被盗号或恶意操作的标志
网络环境异常: 同个网络地址下存在多号, 而且号的资料雷同, **被系统判定微信营销网络环境**
设备信息异常: 如果你的设备被检测为已被root或jailbreak, 以及同个设备存在多个账号, 或被封过多次号, 微信可能会限制登录
账户异常行为: 如果你的微信账户在短时间内有大量的添加好友、发广告等异常行为, 微信可能会对你的账户进行限制
