### ISSUE TITLE
[Bug]: @bot in group chat not work 

### ISSUE THREAD

**Issue by jjyyfff** [iuiaoin/wechat-gptbot#47]
### Search for answers in existing issues

- [X] I have searched issues, there is no similar issue related

### Feature description

新手第一次用。似乎没找到群聊的配置，是没开发呢还是我不会设置？

**Comment by iuiaoin** [comment]
@jjyyfff 你说的群聊配置是指？群聊里@机器人就可以回复了

**Comment by jjyyfff** [comment]
不需要在json里设置哪些群是用机器人回复的？比如这样：

 "group_name_white_list": [
    "ChatGPT测试群",
    "ChatGPT测试群2"
  ],

我直接用默认 json，在群里@机器人 没动静？

**Comment by jjyyfff** [comment]
看命令行后台，有发送群消息里的“你好@xxx”这样，但没有回复，且后台也没看到反馈输出

**Comment by iuiaoin** [comment]
@jjyyfff 对不需要配置，试一下在输消息的时候@机器人而不是复制粘贴含有"@"的消息，就像你平常在群聊里@某个人一样

**Comment by iuiaoin** [comment]
@maq917 之前有个支持在群里任意位置@的pr，这里可以优化一下，目前复制的消息不会被识别为@类型消息

**Comment by maq917** [comment]
[已定位失效原因并修改代码](https://github.com/iuiaoin/wechat-gptbot/pull/50)

**Comment by jjyyfff** [comment]
没有复制，是按平时普通群聊@那样，但无效啊。

@maq917 兄弟，你怎么做到的？要改代码？晕哦。

@iuiaoin 说明代码有问题啊

**Comment by jjyyfff** [comment]
现在在运行，依然是：私聊可以，群聊不行。

**Comment by jjyyfff** [comment]
已经按maq917的修正改了代码，还是老样子。。。。呃

**Comment by jjyyfff** [comment]
@iuiaoin 没有复制，是按平时普通群聊@那样。。。

**Comment by iuiaoin** [comment]
@jjyyfff 我fix了一下，拉最新的代码试一下？

**Comment by jjyyfff** [comment]
@iuiaoin 恭喜您！群聊正常。
