### ISSUE TITLE
[Bug]: 更新到新版之后在群里at 机器人无任何回复

### ISSUE THREAD

**Issue by goxofy** [iuiaoin/wechat-gptbot#49]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.8

### Issue description

LOG如下
```
[INFO][2023-07-14 15:57:58][wechat.py:90] - message received: Message(room_id=18107XXXXX0@chatroom, sender_id=surfee, sender_name=ㅤTink, receiver_id=wxid_vz4g37XXXXXX12, receiver_name=锅巴, content=@锅巴 冯旸赫是谁, type=1, is_group=True, create_time=2023-07-14 15:57:57, at_list=['<![CDATA[wxid_vz4g37XXXXXX12]]>'])
```

**Comment by maq917** [comment]
[解决群聊@失效问题](https://github.com/iuiaoin/wechat-gptbot/pull/50)
