### ISSUE TITLE
[Bug]: 突然不行了。私聊、群聊都不行

### ISSUE THREAD

**Issue by jjyyfff** [iuiaoin/wechat-gptbot#53]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

other

### Issue description

[INFO][2023-07-15 14:06:54][wechat.py:40] - App startup successfully!
[INFO][2023-07-15 14:06:54][wechat.py:178] - [Websocket] connected
[ERROR][2023-07-15 14:07:20][wechat.py:184] - [Websocket] Error: "Message" object has no field "_raw_msg"
[ERROR][2023-07-15 14:07:37][wechat.py:184] - [Websocket] Error: "Message" object has no field "_raw_msg"
[ERROR][2023-07-15 14:08:10][wechat.py:184] - [Websocket] Error: "Message" object has no field "_raw_msg"
[ERROR][2023-07-15 14:08:36][wechat.py:184] - [Websocket] Error: "Message" object has no field "_raw_msg"

**Comment by iuiaoin** [comment]
@jjyyfff 无法复现，你的python版本是在3.8～3.10之间吗？#47 之后没有_raw_msg相关的改动啊

**Comment by jjyyfff** [comment]
呃，我的是3.11.4，最新稳定版。

可奇怪的是，之前都行啊

**Comment by iuiaoin** [comment]
@jjyyfff 3.11不保证能work，因为有些依赖对python版本有要求，要不你切到3.10试试？

**Comment by jjyyfff** [comment]
好，我试试

**Comment by jjyyfff** [comment]
安装3.0.11，

然后 pip install -r requirements.txt

问题解决。

谢谢

**Comment by ghjimlee** [comment]
> 安装3.0.11，
> 
> 然后 pip install -r requirements.txt
> 
> 问题解决。
> 
> 谢谢

亲，你是安装的3.10.11的python版本可以了么，我装的3.10.12不行，也是报这个错，不知道是python版本问题还是包的版本问题

**Comment by ghjimlee** [comment]
![image](https://github.com/iuiaoin/wechat-gptbot/assets/24681381/f8407da4-fe24-4775-b20a-83d20cbca944)
![image](https://github.com/iuiaoin/wechat-gptbot/assets/24681381/c8a83a85-c3a9-4e2b-b4a9-099a401d1bda)
重新建立了python3.10.11的虚拟环境，然后安装依赖报错（之前的也会），然后删了几个的版本号，自己解决冲突，启动后发消息还是会报这个错，请教大神是什么原因呢

**Comment by iuiaoin** [comment]
@ghjimlee 我更新了依赖版本, 再试下?
```
git pull
pip install -r requirements.txt
```

**Comment by ghjimlee** [comment]
可以啦，非常感谢！
