### ISSUE TITLE
[Feat]: 如何更新版本呢？Commits里面更新了bot/chatgpt.py，我该如何更新呢？

### ISSUE THREAD

**Issue by Cyrus-Reed** [iuiaoin/wechat-gptbot#56]
### Search for answers in existing issues

- [X] I have searched issues, there is no similar issue related

### Feature description

Commits里面更新了bot/chatgpt.py，我该如何更新呢？是要从克隆项目步骤开始重新安装一遍吗？

### Motivation

Commits里面更新了bot/chatgpt.py，我该如何更新呢？是要从克隆项目步骤开始重新安装一遍吗？

**Comment by iuiaoin** [comment]
直接git pull最新的代码即可
