### ISSUE TITLE
[Bug]: 最新的 commit 下载下来机器人群聊@不会发消息

### ISSUE THREAD

**Issue by 1014156094** [iuiaoin/wechat-gptbot#57]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.9

### Issue description

[chore: decouple cmd logic (](https://github.com/iuiaoin/wechat-gptbot/commit/0f3e9524f91ccd7cc44a3948746ee21634acb062)https://github.com/iuiaoin/wechat-gptbot/pull/54[)](https://github.com/iuiaoin/wechat-gptbot/commit/0f3e9524f91ccd7cc44a3948746ee21634acb062)
只收了消息没发出消息

**Comment by iuiaoin** [comment]
可以麻烦贴一下log吗？

**Comment by 1014156094** [comment]
> 

我发现用回以前的版本我群聊不了了，群聊@后没自动回复，私聊倒是回自动回复了

**Comment by iuiaoin** [comment]
> > 
> 
> 我发现用回以前的版本我群聊不了了，群聊@后没自动回复，私聊倒是回自动回复了

更新一下最新的代码，by the way不太理解你的问题，你的标题是最新的commit之后群聊不回复, 这条commet是说以前的版本群聊不了，所以到底是哪个版本不work😅

**Comment by 1014156094** [comment]
我先排查看看

**Comment by 1014156094** [comment]
试了好几个版本，也重启了电脑，也重装了依赖，都不行，以下是最新版本
![image](https://github.com/iuiaoin/wechat-gptbot/assets/16074662/ca2928d0-756d-4ba7-8ee9-3e27d31b683d)

**Comment by iuiaoin** [comment]
@1014156094 从log看你@的名字是AI贾维斯，但是bot名字是贾总，所以is_at判断是false，试试@贾总？

**Comment by 1014156094** [comment]
> @1014156094 从log看你@的名字是AI贾维斯，但是bot名字是贾总，所以is_at判断是false，试试@贾总？

按你说的好了，以前是@群昵称也可以的，现在竟然不行了，那我改下微信昵称

**Comment by 1014156094** [comment]
![image](https://github.com/iuiaoin/wechat-gptbot/assets/16074662/9565f168-de6f-4dc3-b1ae-821108b832b2)
可能是single_chat_prefix失效了

**Comment by iuiaoin** [comment]
> ![image](https://github.com/iuiaoin/wechat-gptbot/assets/16074662/9565f168-de6f-4dc3-b1ae-821108b832b2)
> 
> 可能是single_chat_prefix失效了

群聊的方式一直是@机器人昵称，single_chat_prefix只对单聊生效

**Comment by 1014156094** [comment]
那就奇怪了，我以前确实@群昵称是可以的哈哈哈
