### ISSUE TITLE
[Bug]: tiktok 插件装不上

### ISSUE THREAD

**Issue by 1014156094** [iuiaoin/wechat-gptbot#58]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.9

### Issue description

![image](https://github.com/iuiaoin/wechat-gptbot/assets/16074662/7db33c0d-8612-434e-8680-d3b9a1d5632b)

![image](https://github.com/iuiaoin/wechat-gptbot/assets/16074662/0148d73e-62c3-4d12-b775-6ea21d260e50)

tiktok 插件装不上，群聊能正常回复

**Comment by 1014156094** [comment]
我试了下，开了VPN的情况下会装不上

**Comment by iuiaoin** [comment]
@1014156094 这个是网络问题，把github.com加入你vpn的黑名单(或者白名单?), 或者换个能连上github的vpn(逃

**Comment by 1014156094** [comment]
可能吧，但我VPN开的是全局模式的

**Comment by iuiaoin** [comment]
> 可能吧，但我VPN开的是全局模式的

那就加黑名单
