### ISSUE TITLE
[Feat]: 可以添加一个每10轮对话总结之前所有对话历史并加深记忆的功能吗

### ISSUE THREAD

**Issue by AOAOOAOA** [iuiaoin/wechat-gptbot#60]
### Search for answers in existing issues

- [X] I have searched issues, there is no similar issue related

### Feature description

我尝试使用这个项目做一个客服机器人，它可以记下产品参数，在一开始的几轮对话中都可以和测试人员尽职的对话并讲解产品，但是多轮对话后，它依然在完美的扮演客服人员这个职业，产品参数却忘记了，开始用自己搜索出来的一些知识编造回复，所以我希望能加上一个每隔几轮对话总结历史记录，巩固它自己记忆的功能。

**Comment by iuiaoin** [comment]
可以通过调大max_tokens来增大多轮对话的context, 目前最大支持32k(使用gpt-4-32k), ,推荐gpt-3.5-turbo-16k
