### ISSUE TITLE
[Bug]: Azure service issues

### ISSUE THREAD

**Issue by wangxing7714436** [iuiaoin/wechat-gptbot#64]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.8

### Issue description

![1690114179887](https://github.com/iuiaoin/wechat-gptbot/assets/31149248/88f3d50a-c92d-434d-a288-32b56cc41019)

config set the use_azure api = true, however still request an openai endpoint.
my azure endpoint is like https://xxxxx.openai.azure.com/openai/deployments/chatbot/chat/completions?api-version=2023-03-15-preview

**Comment by iuiaoin** [comment]
According to your screenshot, `openai_api_base` and `model` are empty, and yet they need to be filled with valid values to make azure service work.
