### ISSUE TITLE
[Feat]: 给自定义的插件传递参数

### ISSUE THREAD

**Issue by undefinedcodezhong** [iuiaoin/wechat-gptbot#72]
### Search for answers in existing issues

- [X] I have searched issues, there is no similar issue related

### Feature description

怎么给自定义的插件传递参数？示例的tiktok是命令式的，怎么给它附加参数，就是用户输入command后加入搜索参数，让插件功能更丰富

**Comment by iuiaoin** [comment]
@undefinedcodezhong 命令式的调用目前暂时只能使用模式匹配的方式，之后集成了 [function calling](https://openai.com/blog/function-calling-and-other-api-updates) 应该会对用户更加友好, 有个issue在track: #30
