### ISSUE TITLE
[Bug]: 更新到最新版后报错了

### ISSUE THREAD

**Issue by Cyrus-Reed** [iuiaoin/wechat-gptbot#79]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.10

### Issue description

更新到最新版后报错了，我先git pull，然后pip install -r requirements.txt，每次都是这样步骤更新的，但刚刚更新完再打开app.py就报错了。
<img width="477" alt="error" src="https://github.com/iuiaoin/wechat-gptbot/assets/134946188/a405861e-e275-4058-80c3-31ab663f9ed1">

### Repro steps

1. git pull
2. pip install -r requirements.txt
3. config.json
4. bug

**Comment by GH6324** [comment]
同样的问题

**Comment by iuiaoin** [comment]
Seems related to the latest PR #77, could you help to take a look this issue? @ishaan-jaff

**Comment by ishaan-jaff** [comment]
@iuiaoin taking a look

**Comment by ishaan-jaff** [comment]
@Cyrus-Reed sorry about that, I made a fix PR for the same

**Comment by ishaan-jaff** [comment]
@Cyrus-Reed can you try 
in requirements.txt can you make 
`pydantic==2.1.1` and then retry 

```
git pull
pip install -r requirements.txt
config.json
```

please let me know if it fixes the problem

**Comment by iuiaoin** [comment]
> @Cyrus-Reed sorry about that, I made a fix PR for the same

Thanks for the fix, the PR has been merged

**Comment by iuiaoin** [comment]
@Cyrus-Reed I have bumped `litellm` version to 0.1.365, this error should be mitigated.
