### ISSUE TITLE
[Bug]: query key查询使用量的方法失效了。

### ISSUE THREAD

**Issue by JBillH** [iuiaoin/wechat-gptbot#82]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.10

### Issue description

[Bug]: query key查询使用量的方法失效了。
貌似/v1/dashboard/billing/subscription也要session key了。

### Repro steps

send #query key 

### Relevant log output

```shell
{
  "error": {
    "message": "Your request to GET /v1/dashboard/billing/subscription must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
```

**Comment by iuiaoin** [comment]
@maq917 Could you help to take a look on this? Thx~
